export const TYPE_ADD_ACTIVE_SITE = 'TYPE_ADD_ACTIVE_SITE';
export const TYPE_SET_ACTIVE_SITE = 'TYPE_SET_ACTIVE_SITE';
export const TYPE_SET_CHOSEN_TYPE = 'TYPE_SET_CHOSEN_TYPE';


export const TYPE_ADD_USER = 'TYPE_ADD_USER';
export const TYPE_SET_ACTIVE_USER = 'TYPE_SET_ACTIVE_USER';