export const SET_ACTIVE_SITE = 'SET_ACTIVE_SITE';
export const SET_AGE_RANGE = 'SET_AGE_RANGE';
export const SET_TEXT_TO_SEND = 'SET_TEXT_TO_SEND';

export const ADD_USERS = 'ADD_USERS';
export const START_SENDING = 'START_SENDING';
export const ADD_USER_TO_RECEIVED = 'ADD_USER_TO_RECEIVED';

export const ACTIVATE_SENDING_BY_TEMPLATE = 'ACTIVATE_SENDING_BY_TEMPLATE';